title: Usha Dasari
description: Data Analyst | Pharma Graduate
layout: sidebar
style: light
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
permalink: /:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
    values:
      layout: "post"
projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
social_media:
  linkedin: www.linkedin.com/in/dasariusha
  email: dasariusha45@gmail.com
  resume: /Resume.pdf
topics:
  - name: Power BI
    web_url: https://github.com/topics/powerbi
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/power-bi/power-bi.png
  - name: SQL
    web_url: https://github.com/topics/sql
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/sql/sql.png
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
