title: Usha Dasari
description: Data Analyst | Pharma Graduate
layout: sidebar
style: light
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
permalink: /:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
    values:
      layout: "post"
projects:
  sort_by: pushed
  limit: 9
  exclude:
    archived: false
    forks: true
social_media:
  linkedin: dasariusha
  email: dasariusha45@gmail.com

# The line below creates your resume button
description_html: >
  <br>
  <a href="./Usha_Rani_Resume.pdf" target="_blank" style="display: inline-block; background-color: #24292e; color: white; padding: 8px 16px; text-decoration: none; border-radius: 6px; font-size: 14px; font-weight: bold; margin-top: 10px;">
    📄 Download Resume
  </a>

topics:
  - name: Power BI
    web_url: https://github.com/topics/powerbi
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/power-bi/power-bi.png
  - name: SQL
    web_url: https://github.com/topics/sql
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/sql/sql.png
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
